services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - WEBAPP_URL=${WEBAPP_URL:-http://localhost:5173}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - SMS_PROVIDER=${SMS_PROVIDER:-dummy}
      - SMS_API_KEY=${SMS_API_KEY:-}
      - SMS_WEBHOOK_SECRET=${SMS_WEBHOOK_SECRET:-}
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    profiles:
      - prod