version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: onlinesim_frontend
    environment:
      - NODE_ENV=production
    networks:
      - onlinesim_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onlinesim_backend
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - onlinesim_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram_bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: onlinesim_telegram_bot
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - onlinesim_network

  nginx:
    image: nginx:alpine
    container_name: onlinesim_nginx
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - onlinesim_network

volumes:
  backend_data:

networks:
  onlinesim_network:
    driver: bridge