version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: onlinesim_backend
    ports:
      - "9080:8000"  # Второй проект на порту 9080
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  telegram_bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: onlinesim_telegram_bot
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: